**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

# I. NumPy.

0. Імпортувати numpy загальноприйнятим способом.

In [1]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [2]:
grades = [85, 90, 78, 92, 88, 76, 95, 89]

grades_array = np.array(grades)
print(grades_array)

[85 90 78 92 88 76 95 89]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [3]:
prices = [
    [12.5, 10.0, 25.0, 50.0],
    [13.0, 9.5, 24.5, 48.0],
    [12.0, 10.5, 26.0, 51.0],
]

prices_matrix = np.array(prices)
print(prices_matrix)

[[12.5 10.  25.  50. ]
 [13.   9.5 24.5 48. ]
 [12.  10.5 26.  51. ]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [4]:
grades = [85, 90, 78, 92, 88, 76, 95, 89]
grades_array = np.array(grades)

prices = [
    [12.5, 10.0, 25.0, 50.0],
    [13.0, 9.5, 24.5, 48.0],
    [12.0, 10.5, 26.0, 51.0],
]
prices_matrix = np.array(prices)

grades_dtype = grades_array.dtype
prices_dtype = prices_matrix.dtype

print({grades_dtype})
print({prices_dtype})

{dtype('int64')}
{dtype('float64')}


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
grades = [85, 90, 78, 92, 88, 76, 95, 89]
grades_array = np.array(grades)

prices = [
    [12.5, 10.0, 25.0, 50.0],
    [13.0, 9.5, 24.5, 48.0],
    [12.0, 10.5, 26.0, 51.0],
]
prices_matrix = np.array(prices)

grades_shape = grades_array.shape
prices_shape = prices_matrix.shape

print({grades_shape})
print({prices_shape})

{(8,)}
{(3, 4)}


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [6]:
sales_growth = np.linspace(0, 1000.50, 7)
print(sales_growth)

[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [7]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

horizontal_concat = np.hstack((array1, array2))
vertical_concat = np.vstack((array1, array2))

print(array1)
print(array2)

print(horizontal_concat)
print(vertical_concat)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [8]:
def transpose_array(array):

    if len(array.shape) != 2:
        raise ValueError("0")

    transposed = array.reshape(array.shape[1], array.shape[0])
    return transposed


matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = transpose_array(matrix)

print(matrix)
print(transposed_matrix)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [9]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

addition = array1 + array2
subtraction = array1 - array2
scalar_multiplication = array1 * 88
elementwise_multiplication = array1 * array2
matrix_multiplication = np.dot(array1, array2)

print(array1)
print(array2)

print(addition)
print(subtraction)
print(scalar_multiplication)
print(elementwise_multiplication)
print(matrix_multiplication)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 88 176]
 [264 352]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [10]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

min_value = np.min(matrix)
max_value = np.max(matrix)
sum_value = np.sum(matrix)
min_row_values = np.min(matrix, axis=1)
max_col_values = np.max(matrix, axis=0)

print("matrix")
print(matrix)

print("min")
print(min_value)

print("max")
print(max_value)

print("sum")
print(sum_value)

print("min for each rwo")
print(min_row_values)

print("max for each row")
print(max_col_values)

matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
min
1
max
9
sum
45
min for each rwo
[1 4 7]
max for each row
[7 8 9]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [11]:
matrix = np.array([[1, 2, 2], [3, 4, 4], [5, 1, 1]])

unique_values, counts = np.unique(matrix, return_counts=True)
print(matrix)

for value, count in zip(unique_values, counts):
    print(f"value: {value}, coumt: {count}")

[[1 2 2]
 [3 4 4]
 [5 1 1]]
value: 1, coumt: 3
value: 2, coumt: 2
value: 3, coumt: 1
value: 4, coumt: 2
value: 5, coumt: 1


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [12]:
import pandas as pd

In [13]:
import numpy as np

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [14]:
data = [
    ['Johnathan', 'Jhon', '1990-12-15', 75, True],
    ['Kaluchiski', 'Robert', '1985-11-13', 60, False],
    ['Trumphel', 'Donald', '2000-03-20', np.nan, True],
    ['Giovani', 'Carlos', '1995-08-09', 120, False]
]

In [15]:
df = pd.DataFrame(data, columns=['Surname', 'Name', 'DoB', 'Weight', 'Med polis'])

print(df.dtypes)
print(df)

Surname       object
Name          object
DoB           object
Weight       float64
Med polis       bool
dtype: object
      Surname    Name         DoB  Weight  Med polis
0   Johnathan    Jhon  1990-12-15    75.0       True
1  Kaluchiski  Robert  1985-11-13    60.0      False
2    Trumphel  Donald  2000-03-20     NaN       True
3     Giovani  Carlos  1995-08-09   120.0      False


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [16]:
df = pd.read_csv('missile_attacks_daily.csv')
print(df)
print(df.dtypes)

            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primorsko-Akhtarsk and Kursk oblast and Bryans..

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [17]:
df = pd.read_csv('missile_attacks_daily.csv')
print(df.head(10))

         time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
5  2025-01-15 20:00  2025-01-16 09:00    Shahed-136/131   
6  2025-01-15 06:00  2025-01-15 08:00         X-59/X-69   
7  2025-01-15 06:00  2025-01-15 08:00         X-22/X-32   
8  2025-01-15 06:00  2025-01-15 08:00       X-101/X-555   
9  2025-01-15 06:00  2025-01-15 08:00            Kalibr   

                                        launch_place       target  carrier  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine      NaN   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine      NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine      NaN   
3                 Bryansk oblast and V

14. Отримайте інформацію про форму датафрейму.

In [18]:
df = pd.read_csv('missile_attacks_daily.csv')
print(df.shape)

(2044, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [20]:
df = pd.read_csv('missile_attacks_daily.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2044 non-null   object 
 1   time_end              2044 non-null   object 
 2   model                 2044 non-null   object 
 3   launch_place          1023 non-null   object 
 4   target                2016 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2041 non-null   float64
 7   destroyed             2044 non-null   int64  
 8   not_reach_goal        157 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           34 non-null     float64
 11  still_attacking       28 non-null     float64
 12  destroyed_details     294 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [21]:
df = pd.read_csv('missile_attacks_daily.csv')
print(df.describe())

          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2041.000000  2044.000000      157.000000             32.000000   
mean     10.609995     7.491683       20.828025              2.312500   
std      21.041038    14.190972       19.877245              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    34.000000        28.000000  
mean      2.000000         2.821429  
std       1.154701         2.931989  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         4.000000  
max       5.000000        10.000000  


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [22]:
df = pd.read_csv('missile_attacks_daily.csv')

unique_counts = df.nunique()
min_unique_column = unique_counts.idxmin()
value_counts = df[min_unique_column].value_counts()

In [23]:
print(value_counts)

launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Дані в цій колонці представлені як словники в рядках, що не є ідеальним для аналізу. В колонці можуть бути пропуски або некоректні дані. Кількість ракет кожного типу відображається окремими рядками, що ускладнює підрахунок загальної кількості запусків. Колонка з мінімальною кількістю унікальних значень може містити статичні дані або дані, що не додають користі для аналізу. Дані можуть містити дублікати рядків.
...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [24]:
print("Before convertatio")
print(df['launched'].dtypes)

df['launched'] = pd.to_numeric(df['launched'], errors='coerce')
df['launched'] = df['launched'].fillna(0).astype('Int64')

Before convertatio
float64


In [25]:
print("After convertation")
print(df['launched'].dtypes)

print("Data check")
print(df['launched'].head())

After convertation
Int64
Data check
0    61
1    39
2    50
3     4
4     2
Name: launched, dtype: Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [26]:
threshold = 0.3 * len(df)
df = df.loc[:, df.count() >= threshold]

In [27]:
print(df.columns)

Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'launched',
       'destroyed', 'source'],
      dtype='object')


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [29]:
initial_rows = len(df)
df['time_start'] = pd.to_datetime(df['time_start'], errors='coerce')
df['time_end'] = pd.to_datetime(df['time_end'], errors='coerce')

df['attack_duration'] = (df['time_end'] - df['time_start']).dt.total_seconds() / 60
df = df.drop_duplicates()
df = df[df['attack_duration'] > 0]

df.reset_index(drop=True, inplace=True)
final_rows = len(df)


removed_rows = initial_rows - final_rows
print(f"Deleted rows -> {removed_rows}")

Deleted rows -> 1610


**місце для текстової відповіді**

Кількість видалених рядків було обчислено за допомогою різниці між початковою кількістю рядків та кінцевою кількістю рядків.

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [30]:
missing_values_rows = df[df.isnull().any(axis=1)]
print(missing_values_rows)

             time_start            time_end                   model  \
25  2025-01-03 12:00:00 2025-01-03 20:00:00               X-59/X-69   
27  2025-01-03 12:00:00 2025-01-03 20:00:00              Iskander-M   
28  2025-01-03 12:00:00 2025-01-03 20:00:00                   C-300   
45  2024-12-25 05:00:00 2024-12-25 10:00:00  X-101/X-555 and Kalibr   
64  2024-12-14 19:00:00 2024-12-15 08:30:00                   C-300   
..                  ...                 ...                     ...   
429 2022-10-06 15:00:00 2022-10-06 20:00:00               Mohajer-6   
430 2022-10-06 09:00:00 2022-10-06 11:30:00          Shahed-136/131   
431 2022-10-06 09:00:00 2022-10-06 11:30:00               Mohajer-6   
432 2022-10-02 00:00:00 2022-10-02 02:00:00          Shahed-136/131   
433 2022-09-29 23:00:00 2022-09-29 23:59:00          Shahed-136/131   

    launch_place                            target  launched  destroyed  \
25           NaN             Dnipropetrovsk oblast         3          3 